<a href="https://colab.research.google.com/github/Ishan-max/Ishan-max/blob/main/Advanced_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Advanced_pandas_sales_dataset.csv')

df

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
...,...,...,...,...,...,...,...,...,...,...,...
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
226,1227,2024-04-02,Dev,Pune,South,Mouse,Accessories,1669,6,0.05,323.13
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

Q1 Dataset Exploration

Perform the following exploratory steps:

Display the first 10 rows

Display the dataset structure using info()

Find the number of rows and columns

Identify the data types of each column

In [ ]:
# Display first 10 Rows

df.head(10)

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [ ]:
# Display the dataset structure using info()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

In [ ]:
# find the number of rows and columns

df.shape

(230, 11)

In [ ]:
# Identify the data types of each columns

df.dtypes

Order_ID        int64
Order_Date     object
Customer       object
City           object
Region         object
Product        object
Category       object
Sales           int64
Quantity        int64
Discount      float64
Profit        float64
dtype: object

Q2 Sales Filtering Analysis

Filter the dataset to display:

Orders where Sales > 3500

Orders where Region = "East" and Sales > 2500

Explain what insights you observe.

In [ ]:
# Orders where sales > 3500

df[df['Sales'] > 3500 ]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
10,1011,2024-06-30,Neha,Delhi,South,Printer,Office,5977,6,0.00,1578.32
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [ ]:
# orders where region = 'East' and sales > 2500

df[(df['Region'] == 'East') & (df['Sales'] > 1500 )]



''' East region has high-performing orders
The displayed records represent orders in the East region with sales above 2500.
Products in the East region are generating significant revenue
These products contribute more to total sales compared to orders below the 2500 threshold.
Sales performance can be analyzed by product
If multiple products appear in the result, you can identify which products are driving higher sales in the East region.
Potential focus area for business growth
Since these orders exceed the sales benchmark of 2500, the East region may be a strong market for premium or high-demand products.'''

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
11,1012,2024-07-22,Arjun,Ahmedabad,East,Laptop,Electronics,2287,5,0.05,443.30
...,...,...,...,...,...,...,...,...,...,...,...
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
216,1217,2024-08-16,Karan,Chennai,East,Monitor,Electronics,2643,5,0.15,78.53
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76

Q3 Customer Purchase Analysis

Identify the top 5 customers based on total sales.

Hint: Use GroupBy with aggregation.

In [ ]:
# Identify the top 5 customers based on total sales

Top_5_Cust = df.groupby('Customer')['Sales'].sum().sort_values(ascending=False).head(5)

Top_5_Cust

Customer
Nitin    59820
Raj      58416
Rahul    52291
Dev      48500
Isha     46818
Name: Sales, dtype: int64

Q4 Regional Sales Performance

Calculate the total sales generated by each region.

Then identify:

Which region generated the highest revenue?

In [ ]:
Sales_by_Region = df.groupby('Region')['Sales'].sum()

Sales_by_Region

# East Region has generated the highest sales

Region
East     232675
North    158210
South    183108
West     170227
Name: Sales, dtype: int64

Q5 Product Performance Analysis

Calculate the total quantity sold for each product.

Which product appears to be the most popular?

In [ ]:
# Total QTY sold for each product

Total_QTY_Sold = df.groupby('Product')['Quantity'].sum().sort_values(ascending=False)

Total_QTY_Sold

# Monitor is the most told product

Product
Monitor       156
Phone         151
Tablet        150
Laptop        140
Mouse         122
Headphones    115
Keyboard      110
Printer       108
Name: Quantity, dtype: int64

Q6 Multi-Level Grouping

Group the dataset by: Region and Category

Calculate the total sales for each combination.

What insights can you drive from this analysis?

In [ ]:
# Multi level grouping

Region_and_Cat = df.groupby(['Region', 'Category'])['Sales'].sum()

Region_and_Cat

# West Region is having the lowest sales and east region is having the highest sales

Region  Category
East    Accessories     57646
        Electronics    160907
        Office          14122
North   Accessories     62052
        Electronics     70023
        Office          26135
South   Accessories     80914
        Electronics     86690
        Office          15504
West    Accessories     64811
        Electronics     84128
        Office          21288
Name: Sales, dtype: int64

Q7 Pivot Table Creation

Create a pivot table showing:

Rows → Region

Columns → Product

Values → Total Sales

Which region sells the most laptops?

In [ ]:
from textwrap import fill
# Pivot Table

Pivot_table = pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum',
    fill_value=0
)

Pivot_table

# East Region Sells to most laptop

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

Q8 Profitability Analysis

Calculate the average profit for each product category.

Which category is most profitable?

In [ ]:
# Avg profit for each category

Avg_profit = df.groupby('Category')['Profit'].mean()

Avg_profit

# Monitor is the most profitable category

Category
Accessories    410.603086
Electronics    396.462114
Office         471.938462
Name: Profit, dtype: float64

Q9 Discount Impact Study

Analyze the relationship between discount and profit.

Tasks:

Calculate the average profit for each discount level

Identify whether higher discounts lead to lower profit

In [ ]:
# Calculate the avg profit

avg_profit_discount = df.groupby('Discount')['Profit'].mean()

avg_profit_discount

avg_profit_discount = (
    df.groupby('Discount', as_index=False)['Profit']
    .mean()
    .sort_values(by='Profit')
)

avg_profit_discount

   Discount      Profit
4      0.20   90.026923
3      0.15  237.191400
2      0.10  346.460513
1      0.05  531.368039
0      0.00  751.210588

Q10 End-to-End Data Wrangling Task

Perform the following workflow:

Filter the dataset where Sales > 3000

Group data by Region and Product

Calculate total sales

Reshape the result into a pivot table

Explain the business insights obtained from this analysis.

In [ ]:
# filtered data

filtered_df = df[df['Sales'] > 3000 ]

filtered_df

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [ ]:
# gruped data

grouped_data = filtered_df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()

grouped_data

   Region     Product  Sales
0    East  Headphones  14469
1    East    Keyboard   9642
2    East      Laptop  44096
3    East     Monitor  16420
4    East       Mouse  19000
5    East       Phone  29500
6    East     Printer   3696
7    East      Tablet  29229
8   North  Headphones   5326
9   North    Keyboard  15653
10  North      Laptop   4540
11  North     Monitor   5087
12  North       Mouse  22209
13  North       Phone  24670
14  North     Printer  17185
15  North      Tablet   3392
16  South  Headphones  10026
17  South    Keyboard  19249
18  South      Laptop  17950
19  South     Monitor  14921
20  South       Mouse  26928
21  South       Phone  18218
22  South     Printer  14143
23  South      Tablet  19613
24   West  Headphones  13898
25   West    Keyboard  33380
26   West      Laptop   5922
27   West     Monitor  14354
28   West       Mouse   3511
29   West       Phone  15653
30   West     Printer  12648
31   West      Tablet  17185

In [ ]:
# Calculate total sales

grouped_data['Sales'].sum()

np.int64(521713)

In [ ]:
# Filter data
filtered_df = df[df['Sales'] > 3000]

# Group by Region and Product
grouped_data = filtered_df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()

# Create Pivot Table
pivot_table = grouped_data.pivot_table(
    index='Region',
    columns='Product',
    values='Sales',
    fill_value=0
)

print(pivot_table)

Product  Headphones  Keyboard   Laptop  Monitor    Mouse    Phone  Printer  \
Region
East        14469.0    9642.0  44096.0  16420.0  19000.0  29500.0   3696.0
North        5326.0   15653.0   4540.0   5087.0  22209.0  24670.0  17185.0
South       10026.0   19249.0  17950.0  14921.0  26928.0  18218.0  14143.0
West        13898.0   33380.0   5922.0  14354.0   3511.0  15653.0  12648.0

Product   Tablet
Region
East     29229.0
North     3392.0
South    19613.0
West     17185.0