<a href="https://colab.research.google.com/github/Ishan-max/Ishan-max/blob/main/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd

df = pd.read_csv('/content/employee_productivity_dataset.csv')
df.head(10)

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune
5,E006,Neha Singh,HR,27.0,Female,Remote,01-06-2023,36.0,3,3.9,42000.0,Mumbai
6,E007,Rahul Das,Finance,40.0,Male,Onsite,07-07-2019,48.0,8,4.7,65000.0,Delhi
7,E008,Pooja Mehta,Marketing,29.0,Female,Hybrid,12-08-2022,42.0,6,4.3,48000.0,Bangalore
8,E009,Sameer Khan,IT,31.0,Male,Remote,30-09-2021,NaN,5,4.1,51000.0,Pune
9,E010,Kiran Nair,HR,26.0,Female,Onsite,05-10-2023,37.0,4,NaN,43000.0,Mumbai

Q1. Handle Missing Values (Basic Cleaning)

Fill missing values using the following:

Age → Median

Salary → Mean

Hours_Worked_Per_Week → Median

Performance_Score → Mean

Display the dataset after handling missing values.

In [29]:
df.fillna({
    'Age': df['Age'].median(),
    'Salary': df['Salary'].mean(),
    'Hours_Worked_Per_Week': df['Hours_Worked_Per_Week'].median(),
    'Performance_Score': df['Performance_Score'].mean()
}, inplace=True)

print(df)

    Employee_ID         Name Department   Age  Gender Work_Mode   Join_Date  \
0          E001  Amit Sharma         IT  25.0    Male    Remote  15-01-2021
1          E002   Riya Patel         HR  30.0  Female    Hybrid  15-02-2020
2          E003  John Mathew    Finance  29.0    Male    Onsite  10-03-2022
3          E004  Sneha Joshi         IT  28.0  Female    Remote  22-04-2021
4          E005  Arjun Verma  Marketing  35.0    Male    Hybrid  18-05-2020
..          ...          ...        ...   ...     ...       ...         ...
245        E006   Neha Singh         HR  27.0  Female    Remote  01-06-2023
246        E007    Rahul Das    Finance  40.0    Male    Onsite  07-07-2019
247        E008  Pooja Mehta  Marketing  29.0  Female    Hybrid  12-08-2022
248        E009  Sameer Khan         IT  31.0    Male    Remote  30-09-2021
249        E010   Kiran Nair         HR  26.0  Female    Onsite  05-10-2023

     Hours_Worked_Per_Week  Projects_Completed  Performance_Score  \
0                     40.0                   5             4.5000
1                     38.0                   4             4.0000
2                     45.0                   6             4.3125
3                     41.0                   5             4.2000
4                     50.0                   7             4.8000
..                     ...                 ...                ...
245                   36.0                   3             3.9000
246                   48.0                   8             4.7000
247                   42.0                   6             4.3000
248                   41.0                   5             4.1000
249                   37.0                   4             4.3125

           Salary   Location
0    50000.000000       Pune
1    45000.000000     Mumbai
2    60000.000000  Bangalore
3    52000.000000      Delhi
4    50666.666667       Pune
..            ...        ...
245  42000.000000     Mumbai
246  65000.000000      Delhi
247  48000.000000  Bangalore
248  51000.000000       Pune
249  43000.000000     Mumbai

[250 rows x 12 columns]

Q2. Label Encoding

Convert these columns into numeric values using Label Encoding:

Gender

Department

Show the updated columns.

In [30]:
from sklearn.preprocessing import LabelEncoder

# Create Lable encoder object

le = LabelEncoder()

# Encode Gender

df['Gender'] = le.fit_transform(df['Gender'])

# Encode Department

df['Department'] = le.fit_transform(df['Department'])

df[['Gender', 'Department']]

     Gender  Department
0         1           2
1         0           1
2         1           0
3         0           2
4         1           3
..      ...         ...
245       0           1
246       1           0
247       0           3
248       1           2
249       0           1

[250 rows x 2 columns]

Q3. One-Hot Encoding Apply One-Hot Encoding on:

Work_Mode

Location

Display the dataset and check how many new columns are created.

In [31]:
# Apply one hot coding on Work_mode and Location

df_encoded = pd.get_dummies(
    df,
    columns=['Work_Mode', 'Location'],
    dtype=int
)

df_encoded

# Number of columns before encoding

before_cols = len(df.columns)

# Number of columns after enconding

after_cols = len(df_encoded.columns)

new_columns = after_cols - before_cols

print("Number of new columns created", new_columns)

# Display newly created columns

new_cols = [col for col in df_encoded.columns
            if col.startswith('Work_Mode_') or col.startswith('Location_')]

print(df_encoded[new_cols])

Number of new columns created 5
     Work_Mode_Hybrid  Work_Mode_Onsite  Work_Mode_Remote  Location_Bangalore  \
0                   0                 0                 1                   0
1                   1                 0                 0                   0
2                   0                 1                 0                   1
3                   0                 0                 1                   0
4                   1                 0                 0                   0
..                ...               ...               ...                 ...
245                 0                 0                 1                   0
246                 0                 1                 0                   0
247                 1                 0                 0                   1
248                 0                 0                 1                   0
249                 0                 1                 0                   0

     Location_Delhi  Location_Mumbai  Location_Pune
0                 0                0              1
1                 0                1              0
2                 0                0              0
3                 1                0              0
4                 0                0              1
..              ...              ...            ...
245               0                1              0
246               1                0              0
247               0                0              0
248               0                0              1
249               0                1              0

[250 rows x 7 columns]

Q4. Normalization (Min-Max Scaling) Normalize the following columns:

Salary

Hours_Worked_Per_Week

Use MinMaxScaler and display results.

In [32]:
from sklearn.preprocessing import MinMaxScaler

# Create scaler object.

scaler = MinMaxScaler()

# Normalize the columns

df[['Salary', 'Hours_Worked_Per_Week']] = scaler.fit_transform(
    df[['Salary', 'Hours_Worked_Per_Week']]
)

print(df[['Salary', 'Hours_Worked_Per_Week']])

       Salary  Hours_Worked_Per_Week
0    0.347826               0.285714
1    0.130435               0.142857
2    0.782609               0.642857
3    0.434783               0.357143
4    0.376812               1.000000
..        ...                    ...
245  0.000000               0.000000
246  1.000000               0.857143
247  0.260870               0.428571
248  0.391304               0.357143
249  0.043478               0.071429

[250 rows x 2 columns]

Q5. Standardization (Scaling) Apply StandardScaler on:

Age,

Projects_Completed

Display the transformed values.

In [33]:
from sklearn.preprocessing import StandardScaler

# Create scaler object
scaler = StandardScaler()

# Apply StandardScaler
df[['Age', 'Projects_Completed']] = scaler.fit_transform(
    df[['Age', 'Projects_Completed']]
)

# Display transformed values
print(df[['Age', 'Projects_Completed']])

          Age  Projects_Completed
0   -1.172018           -0.211604
1    0.000000           -0.916949
2   -0.234404            0.493742
3   -0.468807           -0.211604
4    1.172018            1.199088
..        ...                 ...
245 -0.703211           -1.622295
246  2.344036            1.904433
247 -0.234404            0.493742
248  0.234404           -0.211604
249 -0.937614           -0.916949

[250 rows x 2 columns]

Compare Scaling Methods Apply both :

MinMaxScaler

StandardScaler

On the Salary column. Show both results side by side.

In [34]:
minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

# Apply scaling
df['Salary_MinMax'] = minmax_scaler.fit_transform(df[['Salary']])

df['Salary_Standard'] = standard_scaler.fit_transform(df[['Salary']])

# Display results side by side
print(df[['Salary', 'Salary_MinMax', 'Salary_Standard']])

       Salary  Salary_MinMax  Salary_Standard
0    0.347826       0.347826    -9.745089e-02
1    0.130435       0.130435    -8.283326e-01
2    0.782609       0.782609     1.364312e+00
3    0.434783       0.434783     1.949018e-01
4    0.376812       0.376812    -3.732632e-16
..        ...            ...              ...
245  0.000000       0.000000    -1.266862e+00
246  1.000000       1.000000     2.095194e+00
247  0.260870       0.260870    -3.898036e-01
248  0.391304       0.391304     4.872545e-02
249  0.043478       0.043478    -1.120685e+00

[250 rows x 3 columns]

Q7. Build Preprocessing Pipeline Create a pipeline that:

Applies encoding to categorical columns

Applies scaling to numerical columns

Use:

ColumnTransformer

Pipeline

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Define columns
categorical_cols = ['Department', 'Gender', 'Work_Mode', 'Location']

numerical_cols = [
    'Age',
    'Hours_Worked_Per_Week',
    'Projects_Completed',
    'Performance_Score',
    'Salary'
]

# Create preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('num', StandardScaler(), numerical_cols)
    ]
)

# Create pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor)
])

# Apply pipeline
processed_data = pipeline.fit_transform(df)

print(processed_data)

[[ 0.          0.          1.         ... -0.21160368  0.68522446
  -0.09745089]
 [ 0.          1.          0.         ... -0.9169493  -1.14204076
  -0.82833257]
 [ 1.          0.          0.         ...  0.49374193  0.
   1.36431247]
 ...
 [ 0.          0.          0.         ...  0.49374193 -0.04568163
  -0.38980356]
 [ 0.          0.          1.         ... -0.21160368 -0.77658772
   0.04872545]
 [ 0.          1.          0.         ... -0.9169493   0.
  -1.12068525]]

Q8. Apply Pipeline

Apply the pipeline on the dataset. Display: Transformed dataset Shape of final dataset

In [36]:
# Define columns
categorical_cols = ['Department', 'Gender', 'Work_Mode', 'Location']

numerical_cols = [
    'Age',
    'Hours_Worked_Per_Week',
    'Projects_Completed',
    'Performance_Score',
    'Salary'
]

# Create preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('num', StandardScaler(), numerical_cols)
    ]
)

pipeline = Pipeline([
    ('preprocessor', preprocessor)
])

# Apply pipeline
transformed_data = pipeline.fit_transform(df)

# Convert to DataFrame
transformed_df = pd.DataFrame(
    transformed_data,
    columns=preprocessor.get_feature_names_out()
)


# Display shape of final dataset

print(transformed_df.head())
print("Shape of Final Dataset:", transformed_df.shape)

   cat__Department_0  cat__Department_1  cat__Department_2  cat__Department_3  \
0                0.0                0.0                1.0                0.0
1                0.0                1.0                0.0                0.0
2                1.0                0.0                0.0                0.0
3                0.0                0.0                1.0                0.0
4                0.0                0.0                0.0                1.0

   cat__Gender_0  cat__Gender_1  cat__Work_Mode_Hybrid  cat__Work_Mode_Onsite  \
0            0.0            1.0                    0.0                    0.0
1            1.0            0.0                    1.0                    0.0
2            0.0            1.0                    0.0                    1.0
3            1.0            0.0                    0.0                    0.0
4            0.0            1.0                    1.0                    0.0

   cat__Work_Mode_Remote  cat__Location_Bangalore  cat__Location_Delhi  \
0                    1.0                      0.0                  0.0
1                    0.0                      0.0                  0.0
2                    0.0                      1.0                  0.0
3                    1.0                      0.0                  1.0
4                    0.0                      0.0                  0.0

   cat__Location_Mumbai  cat__Location_Pune      num__Age  \
0                   0.0                 1.0 -1.172018e+00
1                   1.0                 0.0 -1.598721e-17
2                   0.0                 0.0 -2.344036e-01
3                   0.0                 0.0 -4.688072e-01
4                   0.0                 1.0  1.172018e+00

   num__Hours_Worked_Per_Week  num__Projects_Completed  \
0                   -0.411220                -0.211604
1                   -0.868132                -0.916949
2                    0.731059                 0.493742
3                   -0.182765                -0.211604
4                    1.873338                 1.199088

   num__Performance_Score   num__Salary
0                0.685224 -9.745089e-02
1               -1.142041 -8.283326e-01
2                0.000000  1.364312e+00
3               -0.411135  1.949018e-01
4                1.781584 -3.732632e-16
Shape of Final Dataset: (250, 18)