<a href="https://colab.research.google.com/github/Ishan-max/Ishan-max/blob/main/Exploratory_Data_Analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd

df = pd.read_csv('/content/House Price India.csv')
df

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14615,6762830250,42734,2,1.50,1556,20000,1.0,0,0,4,...,1957,0,122066,52.6191,-114.472,2250,17286,3,76,221700
14616,6762830339,42734,3,2.00,1680,7000,1.5,0,0,4,...,1968,0,122072,52.5075,-114.393,1540,7480,3,59,219200
14617,6762830618,42734,2,1.00,1070,6120,1.0,0,0,3,...,1962,0,122056,52.7289,-114.507,1130,6120,2,64,209000
14618,6762830709,42734,4,1.00,1030,6621,1.0,0,0,4,...,1955,0,122042,52.7157,-114.411,1420,6631,3,54,205000
14619,6762831463,42734,3,1.00,900,4770,1.0,0,0,3,...,1969,2009,122018,52.5338,-114.552,900,3480,2,55,146000

Q1. What is the average, median, and standard deviation of house prices?

In [23]:
# Avg, Median and STD



stats = df['Price'].describe()


print("Average (Mean):", stats['mean'])
print("Median:", stats['50%'])
print("Standard Deviation:", stats['std'])

# First we are defining stats value of describe code which shows avg, median, std and other values
# then we are extracting only the required values from the stats variable

Average (Mean): 538932.2183310534
Median: 450000.0
Standard Deviation: 367532.3808039669

Q2. Which number of bedrooms is most common?

In [24]:
# To find the most common number of bedrooms in the dataset, we use the mode. The mode is the value that appears most frequently in a column.

most_common_bedroom = df['number of bedrooms'].mode()[0]

print("The most common number of bedrooms is:", most_common_bedroom)

The most common number of bedrooms is: 3

Q3. Check if the price data is skewed.

In [25]:
# Skewness helps us understand whether the distribution of house prices is symmetric or tilted toward one side.

price_skewness = df['Price'].skew()

print(price_skewness)

4.269297720707116

Q4. What is the average price for each number of bedrooms?

In [26]:
# To find the average house price for each bedroom category, we use the groupby() function and calculate the mean of the Price column for each unique value in the Bedrooms column.

avg_price_by_bedroom = df.groupby('number of bedrooms')['Price'].mean().round(2)

print(avg_price_by_bedroom)

number of bedrooms
1      308963.75
2      398547.57
3      463277.56
4      636198.81
5      775255.03
6      837581.48
7     1016543.90
8     1208454.55
9      776666.33
10     820000.00
11     520000.00
33     640000.00
Name: Price, dtype: float64

Q5.  What is the relationship between living area and price? (Use : Area without Basement).

In [27]:

# To determine the relationship between Area without Basement and Price, we can calculate the correlation coefficient.

correlation = df['living area'].corr(df['Price'])

print('Correlation between living area and price', correlation)

Correlation between living area and price 0.7121694766782514

Q6. Identify any anomalies where houses have high prices but low areas.

In [28]:
# Anomalies (outliers) are houses that have unusually high prices despite having a relatively small living area. One simple approach is to identify houses with:
'''
Price greater than the 75th percentile (high price), and
living area less than the 25th percentile (low area). '''

high_price = df['Price'].quantile(0.75)
low_area = df['living area'].quantile(0.25)

anomalies = df[
         (df['Price'] > high_price) &
         (df['living area'] < low_area)
         ][['Price', 'living area']]

print(anomalies)
#

        Price  living area
81     900000         1330
91     787000         1330
101    657100         1390
174    675000          930
353    712000         1250
...       ...          ...
13962  675000         1300
14034  664950         1180
14277  650000         1380
14482  659000         1180
14578  875000         1160

[88 rows x 2 columns]

Q7. Compare average price based on number of floors and houses with or without waterfront.

In [29]:
# To compare house prices based on both number of floors and waterfront status, we can group the data by these two columns and calculate the average price.

avg_price_df = (df.groupby(['number of floors', 'waterfront present'])['Price'].mean().round(2))

print(avg_price_df)

number of floors  waterfront present
1.0               0                      432372.39
                  1                     1211080.95
1.5               0                      547616.22
                  1                     1232506.57
2.0               0                      635774.21
                  1                     2075931.37
2.5               0                     1087653.76
                  1                     3280000.00
3.0               0                      555809.50
                  1                     1655000.00
3.5               0                     1205875.00
Name: Price, dtype: float64

Q8. Identify the minimum and maximum house price. What does this indicate?

In [32]:
# To find the minimum and maximum house prices, use the min() and max() functions on the Price column.

min_price = df['Price'].min()
max_price = df['Price'].max()

price_range_df = pd.DataFrame({'Minimum Price': [min_price], 'Maximum Price': [max_price]})

price_range_df

   Minimum Price  Maximum Price
0          78000        7700000

A large gap between the minimum and maximum prices indicates that the housing market contains properties from different price segments, such as affordable homes and luxury properties.

Q9. Which location (zipcode/area) has the highest average price?

In [34]:
# To find the location with the highest average house price, group the data by Zipcode (or Area, depending on your dataset) and calculate the average price for each location.

zipcode_price_df = (
    df.groupby('Postal Code')['Price'].mean().round(2).sort_values(ascending=False).head(1)
)

print(zipcode_price_df)

Postal Code
122071    2348310.81
Name: Price, dtype: float64

Q10. Write at least 5 insights from your analysis.

1. House prices are positively skewed

The skewness of the Price column is greater than 0, indicating that most houses are priced in the lower to middle range, while a small number of luxury properties have very high prices that pull the distribution to the right.

2. Number of bedrooms influences house prices

The average house price generally increases as the number of bedrooms increases. This suggests that larger homes tend to be more expensive because they offer more living space and amenities.

3. Living area has a strong positive relationship with price

The correlation between living area and price is positive, indicating that houses with larger living areas tend to have higher market values. Living area is one of the strongest predictors of house price.

4. Waterfront properties command premium prices

Houses with a waterfront view have a significantly higher average price compared to houses without waterfront access. Location and scenic views greatly impact property value.

5. There are anomalies in the dataset

A few houses have unusually high prices despite having relatively small living areas. These properties may be located in premium neighborhoods, have luxury features, or represent outliers that deserve further investigation.